"""Fixed relationship conflicts

Revision ID: 30ec619614fe
Revises: c1b97e94e75a
Create Date: 2024-08-02 04:46:18.329171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ec619614fe'
down_revision: Union[str, None] = 'c1b97e94e75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
